### ISSUE TITLE
no proper unicode formatting

### ISSUE THREAD

**Issue by soundslikerust** [kufii/vscode-sql-formatter#2]
no proper unicode formatting

**Comment by kufii** [comment]
I'll need more details, but this is likely an issue with the parent library I'm using https://github.com/zeroturnaround/sql-formatter/issues

If you give me details I could potentially look into submitting a pr to this library, or fork the library in a worst case scenario

**Comment by kufii** [comment]
I decided to fork the parent formatting library to include this fix. Please update
