### ISSUE TITLE
Publish extension to open-vsx.org repository

### ISSUE THREAD

**Issue by hvitoi** [kufii/vscode-sql-formatter#37]
It'd be great to make this extension available on [open-vsx.org](https://open-vsx.org/) repository. 

This way people using **Code - OSS** (compiled directly from [vscode](https://github.com/microsoft/vscode) repo) and **VSCodium** binaries are able to install this extension conveniently. 

Here is a [guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) on how to publish to open-vsx.

And thank you for all the effort on supporting this great sql formatter.

**Comment by etlacker** [comment]
I would love this! In addition, you would need to add an open source license to this utility. This would also be great for using it at my workplace!
